name: "backend-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /src/logs/elk-logs.log  # @TODO Filebeat took logs only from filebeat-logs
  fields:
    - service: backend
  fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "backend"