from schemas.base import *
from schemas.courses import *
from schemas.files import *
from schemas.groups import *
from schemas.homeworks import *
from schemas.lessons import *
from schemas.quizzes import *
from schemas.sessions import *
from schemas.tokens import *
from schemas.users import *
